import * as NodeCrypto from "node:crypto";
import { stableStringify } from "@t3tools/shared/relaySigning";
import * as Exit from "effect/Exit";
import * as Schema from "effect/Schema";

const Uuid = Schema.String.check(
  Schema.isPattern(/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i),
);
const Digest = Schema.String.check(Schema.isPattern(/^[0-9a-f]{64}$/));
const NonNegativeInt = Schema.Int.check(Schema.isGreaterThanOrEqualTo(0));
export const ClaudeHistoryMessage = Schema.Struct({
  type: Schema.Literals(["user", "assistant", "system"]),
  uuid: Uuid,
  session_id: Uuid,
  message: Schema.Json,
  parent_tool_use_id: Schema.NullOr(Schema.String),
  parent_agent_id: Schema.NullOr(Schema.String),
});
const decodeMessages = Schema.decodeUnknownExit(Schema.Array(ClaudeHistoryMessage));

/** Only transport IDs regenerated by forkSession are omitted; semantic/tool lineage stays exact. */
export function proveClaudeHistory(raw: unknown, sessionId: string) {
  const decoded = decodeMessages(raw);
  if (Exit.isFailure(decoded)) return undefined;
  const messages = decoded.value;
  if (
    messages.some((message) => message.session_id !== sessionId) ||
    new Set(messages.map((message) => message.uuid)).size !== messages.length
  )
    return undefined;
  const semantic = messages.map(({ uuid: _uuid, session_id: _sessionId, ...message }) => message);
  return {
    messages,
    digest: NodeCrypto.createHash("sha256").update(stableStringify(semantic)).digest("hex"),
  };
}

export const ClaudeConversationAnchor = Schema.Struct({
  version: Schema.Literal(1),
  providerInstanceId: Schema.String,
  sessionIncarnationId: Schema.String,
  threadId: Schema.String,
  cwd: Schema.String,
  snapshotSessionId: Uuid,
  digest: Digest,
  messageCount: NonNegativeInt,
  completedTurnId: Schema.NullOr(Schema.String),
  checkpointTurnCount: NonNegativeInt,
  checkpointRef: Schema.String,
  checkpointOid: Schema.String,
  sourceRevision: NonNegativeInt,
  turnStartMessageIndices: Schema.Array(Schema.NullOr(NonNegativeInt)),
});
export type ClaudeConversationAnchor = typeof ClaudeConversationAnchor.Type;
const decodeAnchor = Schema.decodeUnknownExit(ClaudeConversationAnchor);
export function readClaudeConversationAnchor(raw: unknown) {
  const decoded = decodeAnchor(raw);
  return Exit.isSuccess(decoded) ? decoded.value : undefined;
}

export const ClaudeIdleHistory = Schema.Struct({
  nativeSessionId: Uuid,
  digest: Digest,
  messageCount: NonNegativeInt,
  lastAssistantUuid: Schema.NullOr(Uuid),
  completedTurnId: Schema.NullOr(Schema.String),
  turnCount: NonNegativeInt,
  turnStartMessageIds: Schema.Array(Schema.NullOr(Uuid)),
});
export type ClaudeIdleHistory = typeof ClaudeIdleHistory.Type;
export const ClaudeExactCursor = Schema.Struct({
  version: Schema.Literal(1),
  providerInstanceId: Schema.String,
  sessionIncarnationId: Schema.String,
  threadId: Schema.String,
  cwd: Schema.String,
  idle: Schema.optionalKey(ClaudeIdleHistory),
  selected: Schema.optionalKey(ClaudeConversationAnchor),
  anchors: Schema.Array(ClaudeConversationAnchor),
});
export type ClaudeExactCursor = typeof ClaudeExactCursor.Type;
const decodeCursor = Schema.decodeUnknownExit(ClaudeExactCursor);
export function readClaudeExactCursor(raw: unknown) {
  const decoded = decodeCursor(raw);
  return Exit.isSuccess(decoded) ? decoded.value : undefined;
}

const decodeNativeEntry = Schema.decodeUnknownExit(Schema.fromJsonString(Schema.JsonObject));
const isUuid = Schema.is(Uuid);
const isJsonObject = Schema.is(Schema.JsonObject);
// SDK forks intentionally omit progress and file undo history, and append a new
// presentation title. None is provider conversation content; every other field
// and record remains in the comparison, including attachments and system data.
const OMITTED_NATIVE_METADATA = new Set([
  "progress",
  "file-history-snapshot",
  "custom-title",
  "ai-title",
  "tag",
]);
export function proveClaudeNativeHistory(
  source: string,
  sessionId: string,
  allowedCwds: ReadonlySet<string>,
  upToMessageId?: string,
) {
  const all: Array<Schema.JsonObject> = [];
  const seen = new Set<string>();
  for (const line of source.split("\n")) {
    if (line.trim().length === 0) continue;
    const decoded = decodeNativeEntry(line);
    if (Exit.isFailure(decoded)) return undefined;
    const row = decoded.value;
    if (typeof row.type !== "string") return undefined;
    if (row.uuid !== undefined) {
      if (!isUuid(row.uuid) || seen.has(row.uuid)) return undefined;
      seen.add(row.uuid);
    }
    if (row.sessionId !== undefined && row.sessionId !== sessionId) return undefined;
    if (row.cwd !== undefined && (typeof row.cwd !== "string" || !allowedCwds.has(row.cwd)))
      return undefined;
    if (row.isSidechain === true) return undefined;
    if (row.forkedFrom !== undefined) {
      const value = row.forkedFrom;
      if (
        !isJsonObject(value) ||
        Object.keys(value).length !== 2 ||
        !isUuid(value.sessionId) ||
        !isUuid(value.messageUuid)
      )
        return undefined;
    }
    all.push(row);
  }
  const boundary =
    upToMessageId === undefined
      ? all.length - 1
      : all.findIndex((row) => row.uuid === upToMessageId);
  if (boundary < 0) return undefined;
  const retained = all.slice(0, boundary + 1);
  const progressParents = new Map(
    retained
      .filter((row) => row.type === "progress" && typeof row.uuid === "string")
      .map((row) => [row.uuid as string, row.parentUuid]),
  );
  const resolveParent = (parent: Schema.Json | undefined) => {
    const visited = new Set<string>();
    while (typeof parent === "string" && progressParents.has(parent)) {
      if (visited.has(parent)) return { valid: false, parent: undefined };
      visited.add(parent);
      parent = progressParents.get(parent);
    }
    return { valid: parent === undefined || parent === null || typeof parent === "string", parent };
  };
  const rows = retained.filter((row) => !OMITTED_NATIVE_METADATA.has(row.type as string));
  if (rows.length === 0) return undefined;
  const ids = new Map<string, number>();
  const normalized: Array<Schema.JsonObject> = [];
  for (const [index, row] of rows.entries()) {
    const parent = resolveParent(row.parentUuid);
    const logical = resolveParent(row.logicalParentUuid);
    if (
      !parent.valid ||
      !logical.valid ||
      (typeof parent.parent === "string" && !ids.has(parent.parent)) ||
      (typeof logical.parent === "string" && !ids.has(logical.parent))
    )
      return undefined;
    const {
      uuid,
      parentUuid: _parentUuid,
      logicalParentUuid: _logicalParentUuid,
      sessionId: nativeSessionId,
      timestamp,
      forkedFrom: _forkedFrom,
      ...semantic
    } = row;
    if (typeof uuid === "string") ids.set(uuid, index);
    normalized.push({
      ...semantic,
      ...(uuid !== undefined ? { uuid: index } : {}),
      ...(parent.parent !== undefined
        ? { parentUuid: typeof parent.parent === "string" ? ids.get(parent.parent)! : null }
        : {}),
      ...(logical.parent !== undefined
        ? {
            logicalParentUuid: typeof logical.parent === "string" ? ids.get(logical.parent)! : null,
          }
        : {}),
      ...(nativeSessionId !== undefined ? { sessionId: "<session>" } : {}),
      // The official fork changes only the final retained transcript timestamp.
      ...(index < rows.length - 1 && timestamp !== undefined ? { timestamp } : {}),
    });
  }
  return {
    rows,
    ids,
    digest: NodeCrypto.createHash("sha256").update(stableStringify(normalized)).digest("hex"),
  };
}

export function isVerifiedClaudeFork(
  sourceSessionId: string,
  source: ReadonlyArray<Schema.JsonObject>,
  fork: ReadonlyArray<Schema.JsonObject>,
) {
  return (
    source.length === fork.length &&
    fork.every((row, index) => {
      const provenance = row.forkedFrom;
      return (
        provenance !== undefined &&
        isJsonObject(provenance) &&
        provenance.sessionId === sourceSessionId &&
        provenance.messageUuid === source[index]?.uuid
      );
    })
  );
}

/** Native SDK0.3.260 path codec. Legacy/ambiguous locations remain ineligible. */
export function claudeProjectDirectoryName(cwd: string) {
  const encoded = cwd.replace(/[^a-zA-Z0-9]/g, "-");
  if (encoded.length <= 200) return encoded;
  let hash = 0;
  for (let index = 0; index < cwd.length; index += 1)
    hash = ((hash << 5) - hash + cwd.charCodeAt(index)) | 0;
  return `${encoded.slice(0, 200)}-${Math.abs(hash).toString(36)}`;
}
export function validClaudeProjectDirectoryOverride(value: string | undefined) {
  return value !== undefined &&
    /^[A-Za-z0-9_-]{1,64}$/.test(value) &&
    !/^(con|prn|aux|nul|com[0-9]|lpt[0-9])$/i.test(value)
    ? value
    : undefined;
}
