import { WS_METHODS } from "@t3tools/contracts";
import * as Crypto from "effect/Crypto";
import { Atom } from "effect/unstable/reactivity";

import {
  createAtomCommandScheduler,
  createEnvironmentCommand,
  createEnvironmentRpcCommand,
} from "./runtime.ts";
import {
  type ArchiveThreadInput,
  type CreateThreadInput,
  type DeleteThreadInput,
  type FollowUpThreadInputQueueInput,
  type InterruptThreadTurnInput,
  type RespondToThreadApprovalInput,
  type RespondToThreadUserInputInput,
  type RevertThreadCheckpointInput,
  type SetThreadInteractionModeInput,
  type SetThreadRuntimeModeInput,
  type PinThreadInput,
  type ReorderPinnedThreadInput,
  type SettleThreadInput,
  type SnoozeThreadInput,
  type StartThreadTurnInput,
  type StopThreadSessionInput,
  type UnarchiveThreadInput,
  type UnpinThreadInput,
  type UnsettleThreadInput,
  type UnsnoozeThreadInput,
  type UpdateThreadMetadataInput,
  archiveThread,
  createThread,
  deleteThread,
  followUpThreadInputQueue,
  interruptThreadTurn,
  respondToThreadApproval,
  respondToThreadUserInput,
  revertThreadCheckpoint,
  setThreadInteractionMode,
  setThreadRuntimeMode,
  pinThread,
  reorderPinnedThread,
  settleThread,
  snoozeThread,
  startThreadTurn,
  stopThreadSession,
  unarchiveThread,
  unpinThread,
  unsettleThread,
  unsnoozeThread,
  updateThreadMetadata,
} from "../operations/commands.ts";
import type { EnvironmentRegistry } from "../connection/registry.ts";

export type {
  ArchiveThreadInput,
  CreateThreadInput,
  DeleteThreadInput,
  FollowUpThreadInputQueueInput,
  InterruptThreadTurnInput,
  RespondToThreadApprovalInput,
  RespondToThreadUserInputInput,
  RevertThreadCheckpointInput,
  SetThreadInteractionModeInput,
  SetThreadRuntimeModeInput,
  PinThreadInput,
  ReorderPinnedThreadInput,
  SettleThreadInput,
  SnoozeThreadInput,
  StartThreadTurnInput,
  StopThreadSessionInput,
  UnarchiveThreadInput,
  UnpinThreadInput,
  UnsettleThreadInput,
  UnsnoozeThreadInput,
  UpdateThreadMetadataInput,
} from "../operations/commands.ts";

export function createThreadEnvironmentAtoms<R, E>(
  runtime: Atom.AtomRuntime<EnvironmentRegistry | Crypto.Crypto | R, E>,
) {
  const scheduler = createAtomCommandScheduler();
  const concurrency = {
    mode: "serial" as const,
    key: ({ environmentId, input }: { environmentId: string; input: { threadId: string } }) =>
      JSON.stringify([environmentId, input.threadId]),
  };
  return {
    create: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:create",
      execute: (input: CreateThreadInput) => createThread(input),
      scheduler,
      concurrency,
    }),
    delete: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:delete",
      execute: (input: DeleteThreadInput) => deleteThread(input),
      scheduler,
      concurrency,
    }),
    archive: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:archive",
      execute: (input: ArchiveThreadInput) => archiveThread(input),
      scheduler,
      concurrency,
    }),
    unarchive: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:unarchive",
      execute: (input: UnarchiveThreadInput) => unarchiveThread(input),
      scheduler,
      concurrency,
    }),
    settle: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:settle",
      execute: (input: SettleThreadInput) => settleThread(input),
      scheduler,
      concurrency,
    }),
    unsettle: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:unsettle",
      execute: (input: UnsettleThreadInput) => unsettleThread(input),
      scheduler,
      concurrency,
    }),
    snooze: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:snooze",
      execute: (input: SnoozeThreadInput) => snoozeThread(input),
      scheduler,
      concurrency,
    }),
    unsnooze: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:unsnooze",
      execute: (input: UnsnoozeThreadInput) => unsnoozeThread(input),
      scheduler,
      concurrency,
    }),
    pin: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:pin",
      execute: (input: PinThreadInput) => pinThread(input),
      scheduler,
      concurrency,
    }),
    unpin: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:unpin",
      execute: (input: UnpinThreadInput) => unpinThread(input),
      scheduler,
      concurrency,
    }),
    reorderPin: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:reorder-pin",
      execute: (input: ReorderPinnedThreadInput) => reorderPinnedThread(input),
      scheduler,
      concurrency,
    }),
    updateMetadata: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:update-metadata",
      execute: (input: UpdateThreadMetadataInput) => updateThreadMetadata(input),
      scheduler,
      concurrency,
    }),
    setRuntimeMode: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:set-runtime-mode",
      execute: (input: SetThreadRuntimeModeInput) => setThreadRuntimeMode(input),
      scheduler,
      concurrency,
    }),
    setInteractionMode: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:set-interaction-mode",
      execute: (input: SetThreadInteractionModeInput) => setThreadInteractionMode(input),
      scheduler,
      concurrency,
    }),
    startTurn: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:start-turn",
      execute: (input: StartThreadTurnInput) => startThreadTurn(input),
      scheduler,
      concurrency,
    }),
    followUpInputQueue: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:follow-up-input-queue",
      execute: (input: FollowUpThreadInputQueueInput) => followUpThreadInputQueue(input),
      scheduler,
      concurrency,
    }),
    interruptTurn: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:interrupt-turn",
      execute: (input: InterruptThreadTurnInput) => interruptThreadTurn(input),
      scheduler,
      concurrency,
    }),
    respondToApproval: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:respond-to-approval",
      execute: (input: RespondToThreadApprovalInput) => respondToThreadApproval(input),
      scheduler,
      concurrency,
    }),
    respondToUserInput: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:respond-to-user-input",
      execute: (input: RespondToThreadUserInputInput) => respondToThreadUserInput(input),
      scheduler,
      concurrency,
    }),
    respondToInteraction: createEnvironmentRpcCommand(runtime, {
      label: "environment-data:commands:thread:respond-to-interaction",
      tag: WS_METHODS.providerRespondToInteraction,
      scheduler,
      concurrency,
    }),
    revertCheckpoint: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:revert-checkpoint",
      execute: (input: RevertThreadCheckpointInput) => revertThreadCheckpoint(input),
      scheduler,
      concurrency,
    }),
    recoverRollback: createEnvironmentRpcCommand(runtime, {
      label: "environment-data:commands:thread:recover-rollback",
      tag: WS_METHODS.rollbackRecover,
      scheduler,
      concurrency,
    }),
    askSessionSideQuestion: createEnvironmentRpcCommand(runtime, {
      label: "environment-data:commands:thread:ask-session-side-question",
      tag: WS_METHODS.providerAskSessionSideQuestion,
      scheduler,
      // The unary ask can remain open until the provider settles it. It must
      // not occupy the thread's serial lane or its cancel command could not run.
      concurrency: { mode: "parallel" },
    }),
    cancelSessionSideQuestion: createEnvironmentRpcCommand(runtime, {
      label: "environment-data:commands:thread:cancel-session-side-question",
      tag: WS_METHODS.providerCancelSessionSideQuestion,
      scheduler,
      concurrency: { mode: "parallel" },
    }),
    cancelSessionAgent: createEnvironmentRpcCommand(runtime, {
      label: "environment-data:commands:thread:cancel-session-agent",
      tag: WS_METHODS.providerCancelSessionAgent,
      scheduler,
      concurrency,
    }),
    messageSessionAgent: createEnvironmentRpcCommand(runtime, {
      label: "environment-data:commands:thread:message-session-agent",
      tag: WS_METHODS.providerMessageSessionAgent,
      scheduler,
      concurrency,
    }),
    reloadSessionResources: createEnvironmentRpcCommand(runtime, {
      label: "environment-data:commands:thread:reload-session-resources",
      tag: WS_METHODS.providerReloadSessionResources,
      scheduler,
      concurrency,
    }),
    getSessionAgentDepth: createEnvironmentRpcCommand(runtime, {
      label: "environment-data:commands:thread:get-session-agent-depth",
      tag: WS_METHODS.providerGetSessionAgentDepth,
      scheduler,
      concurrency,
    }),
    setSessionAgentDepth: createEnvironmentRpcCommand(runtime, {
      label: "environment-data:commands:thread:set-session-agent-depth",
      tag: WS_METHODS.providerSetSessionAgentDepth,
      scheduler,
      concurrency,
    }),
    getSessionInputQueue: createEnvironmentRpcCommand(runtime, {
      label: "environment-data:commands:thread:get-session-input-queue",
      tag: WS_METHODS.providerGetSessionInputQueue,
      scheduler,
      concurrency,
    }),
    clearSessionInputQueue: createEnvironmentRpcCommand(runtime, {
      label: "environment-data:commands:thread:clear-session-input-queue",
      tag: WS_METHODS.providerClearSessionInputQueue,
      scheduler,
      concurrency,
    }),
    removeOnlySessionInputQueueItem: createEnvironmentRpcCommand(runtime, {
      label: "environment-data:commands:thread:remove-only-session-input-queue-item",
      tag: WS_METHODS.providerRemoveOnlySessionInputQueueItem,
      scheduler,
      concurrency,
    }),
    setSessionInputQueueMode: createEnvironmentRpcCommand(runtime, {
      label: "environment-data:commands:thread:set-session-input-queue-mode",
      tag: WS_METHODS.providerSetSessionInputQueueMode,
      scheduler,
      concurrency,
    }),
    getSessionCompaction: createEnvironmentRpcCommand(runtime, {
      label: "environment-data:commands:thread:get-session-compaction",
      tag: WS_METHODS.providerGetSessionCompaction,
      scheduler,
      concurrency,
    }),
    compactSession: createEnvironmentRpcCommand(runtime, {
      label: "environment-data:commands:thread:compact-session",
      tag: WS_METHODS.providerCompactSession,
      scheduler,
      concurrency,
    }),
    abortSessionCompaction: createEnvironmentRpcCommand(runtime, {
      label: "environment-data:commands:thread:abort-session-compaction",
      tag: WS_METHODS.providerAbortSessionCompaction,
      scheduler,
      concurrency,
    }),
    setSessionAutoCompaction: createEnvironmentRpcCommand(runtime, {
      label: "environment-data:commands:thread:set-session-auto-compaction",
      tag: WS_METHODS.providerSetSessionAutoCompaction,
      scheduler,
      concurrency,
    }),
    refineSessionHarness: createEnvironmentRpcCommand(runtime, {
      label: "environment-data:commands:thread:refine-session-harness",
      tag: WS_METHODS.providerRefineSessionHarness,
      scheduler,
      concurrency,
    }),
    stopSession: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:stop-session",
      execute: (input: StopThreadSessionInput) => stopThreadSession(input),
      scheduler,
      concurrency,
    }),
    uploadFeedback: createEnvironmentRpcCommand(runtime, {
      label: "environment-data:commands:thread:upload-feedback",
      tag: WS_METHODS.providerUploadFeedback,
      scheduler,
      concurrency,
    }),
  };
}
